[dataset]
root = "./datasets/Landscape-Dataset"
img_suffix = 'jpg'
img_size = 224
angle_num = 8
train_ratio = 0.9
val_ratio = 0.05
test_ratio = 0.05

[train]
lr = 0.0004
lr_scheduler = { T_0 = 5, T_mult = 2 }
loss = { lambda_cos = 0.24, exponent = 2 }
epoches = 64
batch_size = 64
num_workers = 12

[test]
batch_size = 128
num_workers = 12
