dataset:
  root: ./datasets/Landscape-Dataset
  img_size: 224
  train_ratio: 0.9
  val_ratio: 0.05
  test_ratio: 0.05

train:
  lr: 0.0008
  lr_scheduler:
    T_0: 5
    T_mult: 2
  loss:
    lambda_cos: 0.24
    exponent: 1.5
  epoches: 35
  batch_size: 48
  steps: 135

evaluate:
  batch_size: 64
