[dataset]
root = "./datasets/Landscape-Dataset"
img_size = 224
train_ratio = 0.9
val_ratio = 0.05
test_ratio = 0.05

[train]
lr = 0.0004
lr_scheduler = { T_0 = 5, T_mult = 2 }
loss = { lambda_cos = 0.24, exponent = 2 }
epoches = 3000
batch_size = 128

[evaluate]
batch_size = 128
