[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
urls = { Repository = "https://github.com/Starry-OvO/rotate-captcha-crack" }
name = "rotate-captcha-crack"
readme = "README.md"
requires-python = ">=3.8,<3.12"
authors = [{ name = "Starry-OvO", email = "starry.qvq@gmail.com" }]
dependencies = [
    "matplotlib<4,>=3.4",
    "tqdm<5,>=4",
    "tomli<3,>=2.0.0;python_version<'3.11'",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.dynamic]
version = { attr = "rotate_captcha_crack.__version__.__version__" }

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ["py38", "py39", "py310", "py311", "py312"]

[tool.ruff]
line-length = 120
target-version = "py38"

[tool.ruff.lint]
select = ["W", "E", "F", "I"]
ignore = ["E402", "E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
